name: detekt

on:
  push:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.1
